name: snipeit_asset_manager
description: Internal IT Asset Management App integrated with Snipe-IT
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  permission_handler: ^12.0.3

  google_fonts: ^8.1.0

  # HTTP client
  http: ^1.6.0
  dio: ^5.9.2

  # Barcode scanning
  mobile_scanner: ^7.2.0

  # Digital signature pad
  signature: ^6.3.0

  # Image conversion utilities
  image: ^4.8.0

  # Environment / config
  flutter_dotenv: ^6.0.1

  # Web file download
  universal_html: ^2.2.4

  # UI utilities
  cupertino_icons: ^1.0.9
  intl: ^0.20.2

  # App icon
  flutter_launcher_icons: ^0.14.4

  qr: ^3.0.1

  pdf: ^3.12.0
  printing: ^5.14.3
  crypto: ^3.0.7
  html_unescape: ^2.0.0
  path_provider: ^2.1.6
  share_plus: ^13.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
    - assets/stream_logoNew.png
    - assets/fonts/Sarabun-Regular.ttf
    - assets/fonts/Sarabun-Bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"